In [0]:
import numpy as np
np.random.seed(10)

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
array = np.random.randint(50, size=(10))

media = array.mean()
desvio = array.std()
media, desvio

Out[9]: (28.7, 17.41866814656046)

### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)

array[array <= 0.5] = np.sqrt(array[array <= 0.5])

array

Out[18]: array([0.10036689, 0.42983577, 0.63648124, 0.28176612, 0.55034537,
       0.52366778, 0.3537827 , 0.9468501 , 0.98004714, 0.57409797])

### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)

max_value = np.amax(matriz, axis=1)

print(
f"""
Matrize:
{matriz}

Matriz máxima:
{max_value}
""")


Matrize:
[[[0.43631021 0.98595873 0.89944699]
  [0.25145528 0.83884437 0.91976339]
  [0.59192093 0.06076954 0.22220391]]

 [[0.03632678 0.06560915 0.03933817]
  [0.32886191 0.20886789 0.63152303]
  [0.27649894 0.67667701 0.84551706]]

 [[0.48785217 0.9970613  0.17640918]
  [0.66794161 0.86983272 0.9644758 ]
  [0.95570877 0.79502997 0.56991322]]]

Matriz máxima:
[[0.59192093 0.98595873 0.91976339]
 [0.32886191 0.67667701 0.84551706]
 [0.95570877 0.9970613  0.9644758 ]]



### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)
print(f"Matrizes: {matriz}")
matriz_media = np.mean(matriz, 1)

subtracao = matriz - matriz_media[:, np.newaxis]
subtracao

Matrizes: [[0.14853345 0.42845074 0.69389007 0.10461974 0.43960524]
 [0.16620215 0.50697863 0.81903586 0.09010673 0.80006875]
 [0.56512635 0.58934771 0.19810066 0.43611826 0.29590376]
 [0.03755768 0.03068484 0.453105   0.74486408 0.55729541]
 [0.3851136  0.1680728  0.83826132 0.5990518  0.78271482]]
Out[34]: array([[-0.2144864 ,  0.06543089,  0.33087022, -0.2584001 ,  0.07658539],
       [-0.31027628,  0.0305002 ,  0.34255744, -0.38637169,  0.32359033],
       [ 0.14820701,  0.17242836, -0.21881869,  0.01919891, -0.12101559],
       [-0.32714372, -0.33401656,  0.0884036 ,  0.38016268,  0.19259401],
       [-0.16952927, -0.38657007,  0.28361845,  0.04440893,  0.22807195]])

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)

diag_1 = np.diag(matriz)
diag_2 = np.diag(np.fliplr(matriz))

media_d1 = np.mean(diag_1)
media_d2 = np.mean(diag_2)

desv_d1 = np.std(diag_1)
desv_d2 = np.std(diag_2)

print(
f"""
Matriz principal:
{matriz}
Diagonal 1:
{diag_1}
Média:
{media_d1:.2f}
Desvio:
{desv_d1:.2f}

Diagonal 2:
{diag_2}
Média:
{media_d2:.2f}
Desvio:
{desv_d2:.2f}
"""
)


Matriz principal:
[[0.36802668 0.80277594 0.62756185 0.82121648]
 [0.28825314 0.27479513 0.60105189 0.9385142 ]
 [0.70729631 0.26340316 0.12233592 0.45872423]
 [0.9748125  0.68057437 0.19325373 0.04673923]]
Diagonal 1:
[0.36802668 0.27479513 0.12233592 0.04673923]
Média:
0.20
Desvio:
0.13

Diagonal 2:
[0.82121648 0.60105189 0.26340316 0.9748125 ]
Média:
0.67
Desvio:
0.27

